### ISSUE TITLE
Possible type hint error

### ISSUE THREAD

**Issue by Leva7** [MoarCatz/nmaps-telegram#46]
https://github.com/MoarCatz/nmaps-telegram/blob/f8b330f1ddc1be319a8d59365e02eebb4c14aee8/roads.py#L10

You are using [`any`](https://docs.python.org/3/library/functions.html#any) as a type hint - a builtin function, not a class. What you're probably looking for is [`typing.Any`](https://docs.python.org/3/library/typing.html#typing.Any)

**Comment by alexbagirov** [comment]
Thanks! Will look into it a little bit later
